spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: manpromanpro
  datasource:
    url: jdbc:postgresql://localhost:15001/manpromanpro
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}
