spring:
  application:
    name: manpromanpro
  datasource:
    url: jdbc:postgresql://localhost:9010/manpromanpro
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update